name: Bug Report
description: Please describe the problem. If possible, include OpenMandriva Lx version, the steps needed to reproduce, and the expected outcome.
labels: [new]
body:
- type: markdown
  attributes:
    value: |
      If you need help with running Minecraft, please visit us on our Discord before making a bug report.
      **Do not forget to give your issue a descriptive title.** "Bug in the instance screen" makes it hard to distinguish issues at a glance.
- type: dropdown
  attributes:
    label: Operating System
    description: If you know this bug occurs on multiple operating systems, select all you have tested.
    multiple: true
    options:
    - Windows
    - macOS
- type: textarea
  attributes:
    label: Description of bug
    description: What did you expect to happen, what happened, and why is it incorrect?
    placeholder: The cat button should show a cat, but it showed a dog instead!
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: A bulleted list, or an exported instance if relevant.
    placeholder: "* Press the cat button"
  validations:
    required: true
- type: textarea
  attributes:
    label: Suspected cause
    description: If you know what could be causing this bug, describe it here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Logs and screenshots if relevant
    description:
  validations:
    required: false
- type: textarea
  attributes:
    label: OpenMandriva version:
    description:
  validations:
    required: false
- type: checkboxes
  attributes:
    label: This issue is unique
    options:
    - label: I have searched the issue tracker and did not find an issue describing my bug.
      required: true
