name: Bug Report
description: Please describe the problem. If possible, include OpenMandriva Lx version, the steps needed to reproduce, and the expected outcome.
labels: [new]
body:
- type: markdown
  attributes:
    value: |
     **Do not forget to give your issue a descriptive title.** "Image browser crashes" makes it hard to distinguish issues at a glance.
- type: checkboxes
  attributes:
    label: This issue is unique
    options:
    - label: I have searched the issue tracker and did not find an issue describing my bug.
      required: true
- type: textarea
  attributes:
    label: OpenMandriva version
    description:
  validations:
    required: false
- type: textarea
  attributes:
    label: Description of bug
    description: What did you expect to happen, what happened, why is it incorrect?
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: A bulleted list
    placeholder: "- Launch gnome-terminal"
  validations:
    required: true
- type: textarea
  attributes:
    label: Suspected cause
    description: If you know what could be causing this bug, describe it here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Observed behavior
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected behavior
    description:
  validations:
    required: false
- type: textarea
  attributes:
    label: Addctional comment, logs and screenshots if relevant
    description:
  validations:
    required: false
